version: '3.4'

services:
  splitter:
    image: tommyafek/splitter
    restart: unless-stopped
    ports:
      - 9001:9001
    env_file: variables.env
    volumes:
      - ./dataSources.ts:/usr/src/app/app/config/dataSources.ts
    depends_on:
      - redis
      - rabbit

  rabbit:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672

  mocksKart:
    image: tommyafek/mock
    restart: unless-stopped
    env_file: mock.env
    ports:
      - 7700:7700

  redis:
    image: bitnami/redis:latest
    user: root
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data

  basicmatch:
    image: tommyafek/basic_match:latest
    env_file: basic_match.env
    volumes:
      - ./src/config/fieldNames.ts:/usr/src/app/app/config/fieldNames.ts
    depends_on:
      - splitter
      - rabbit

  buildentity:
    image: bentity
    restart: unless-stopped
    env_file: buildEntities.env
    depends_on:
      - rabbit

  rgbe:
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - rabbit

  send-to-rabit:
    image: sendtorabbit
    restart: unless-stopped
    env_file: sendToRabbit.env
    depends_on:
      - rabbit
    ports:
      - 7707:7707

  mockapikart:
    image: mockapikart
    restart: unless-stopped
    env_file: mockapikart.env
    depends_on:
      - rabbit
    ports:
      - 7709:7709

volumes:
  redis_data:
    driver: local
